import type { StatutPiece } from "./api";

export const T = {
  appli: "Kaldera",
  horsLigne: "Service momentanément indisponible, vos fichiers n'ont pas été perdus. Reconnexion…",
  introuvable: "Ce dossier est introuvable.",
  connexion: {
    titre: "Connexion à votre espace sinistre",
    identifiant: "Identifiant",
    motDePasse: "Mot de passe",
    bouton: "Se connecter",
    erreur: "Identifiant ou mot de passe incorrect, ou compte momentanément bloqué.",
  },
  sinistres: {
    titre: "Mes sinistres",
    vide: "Aucun sinistre n'est rattaché à votre compte.",
    deconnexion: "Se déconnecter",
    dossier: (reference: string) => `Sinistre ${reference}`,
  },
  etapes: [
    "Demande reçue",
    "Vérification de votre dossier",
    "Évaluation du dommage",
    "Contrôles complémentaires",
    "Décision",
  ],
  branches: {
    attente_pieces: "En attente de vos pièces",
    gestionnaire: "Transmise à un gestionnaire",
  },
  stepper: { titre: "Étapes du dossier", faite: "terminée", courante: "en cours" },
  statut: {
    ecoule: (d: string) => `${d} écoulées`,
    restant: (d: string) => `environ ${d} restantes`,
    termine: "Traitement terminé",
  },
  pieces: {
    titre: "Pièces attendues",
    deposer: "Déposer",
    statuts: {
      a_fournir: "À fournir",
      en_analyse: "En analyse",
      validee: "Validée",
      a_refaire: "À refaire",
    } satisfies Record<StatutPiece, string>,
  },
  depot: {
    titre: "Déposer une pièce",
    type: "Type de pièce",
    types: { facture: "Facture", photo: "Photos des dommages", depot_plainte: "Récépissé de dépôt de plainte" },
    choisir: "Choisir un fichier",
    photo: "Prendre une photo",
    glisser: "ou glissez-déposez le fichier ici (PDF, PNG ou JPEG, 10 Mo au plus)",
    envoyer: "Envoyer la pièce",
    recu: "Pièce reçue, analyse en cours.",
    dejaRecu: "Ce fichier a déjà été déposé.",
    multipage: "Ce PDF compte plusieurs pages : seule la première sera lue. Déposez chaque document séparément.",
    erreurs: {
      409: "Votre dossier a déjà été soumis : il n'est plus possible d'ajouter de pièce.",
      413: "Fichier trop volumineux : 10 Mo au plus.",
      415: "Format non accepté : PDF, PNG ou JPEG uniquement.",
      defaut: "Le dépôt a échoué. Réessayez.",
    } as Record<string, string>,
  },
  soumettre: {
    bouton: "Soumettre mon dossier",
    analyse: "Patientez : une pièce est encore en analyse.",
    soumis: "Dossier soumis.",
    confirmerTitre: "Des pièces manquent encore",
    confirmerTexte:
      "Si vous soumettez maintenant, votre dossier sera transmis à un gestionnaire pour les pièces manquantes. Soumettre quand même ?",
    confirmer: "Soumettre quand même",
    annuler: "Annuler",
  },
  verdict: {
    titre: "Décision",
    issues: {
      acceptee: "Remboursement accordé",
      partielle: "Remboursement partiel accordé",
      refusee: "Demande non prise en charge",
      transmise: "Transmise à un gestionnaire",
    },
    montant: "Montant remboursé",
    franchise: "Franchise",
    retenues: "Pièces prises en compte",
  },
  chat: {
    ouvrir: "Aide sur mes pièces",
    nouveau: "nouveau message",
    titre: "Assistant pièces",
    description: "Posez vos questions sur les pièces de votre dossier.",
    champ: "Votre message",
    envoyer: "Envoyer",
    redaction: "L'assistant rédige sa réponse…",
    compteur: (n: number) => `${n} / 1000`,
    deposer: "Déposer maintenant",
    vous: "Vous",
    agent: "Assistant",
    erreur: "Message non envoyé. Réessayez.",
  },
} as const;
